// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  IntroSidebar: [{type: 'autogenerated', dirName: '01_Introduction'}],
  SchematicSidebar: [{type: 'autogenerated', dirName: '02_Schematic'}],
  LavoutSidebar: [{type: 'autogenerated', dirName: '03_PCB_Layout'}],
  RoutingSidebar: [{type: 'autogenerated', dirName: '04_PCB_Routing'}],
  ManuSidebar: [{type: 'autogenerated', dirName: '05_Manufacturing'}],
  ScriptSidebar: [{type: 'autogenerated', dirName: '06_Scripts'}],
  GlossarySidebar: [{type: 'autogenerated', dirName: '07_Glossary'}],

};

export default sidebars;
